### PR TITLE
Add basic functionality

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
@LAShemilt can you give this a try? There's still quite a few bits that need to be done, but downloading seems to work.

**Comment by LAShemilt** [comment]
not in the PR but in applications.py what is if platform.system()="Darwin" doing...?

**Comment by tschoonj** [comment]
> not in the PR but in applications.py what is if platform.system()="Darwin" doing...?

Darwin refers to macOS. Menu handling is a bit special on that platform...

The same line can be found in the monitor.

**Comment by tschoonj** [comment]
@JossWhittle If you have a moment, could you give this a try? I would like some more feedback on how it behaves on Windows... Thanks!!

**Comment by JossWhittle** [comment]
@tschoonj I'll let you know, I'm trying to get GTK installed at the moment.

**Comment by tschoonj** [comment]
No need, use a conda environment for everything

**Pull request merged**
